service: ${env:CLIENT}-mani
useDotenv: true
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs12.x
  region: ${env:REGION, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  tracing: # this tracks a request through the AWS infrastructure, to figure out bottle-necks, etc. Could reasonably be turned off.
    apiGateway: ${env:XRAY, self:custom.debug}
  logs:
    restApi: ${env:LOG_REST_API, self:custom.debug} # Adds a log stream (we could turn this off).
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeAsync
        - lambda:InvokeFunction
      Resource: '*'
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: '*'

# Warning: the dynamodb shell does NOT work in Firefox, only in Chrome
custom:
  debug: ${env:DEBUG, true} # debug mode (string values or 0|1 are converted)
  dotenv:
    basePath: env/
  output:
    file: client/sls-output.json
  dynamodb:
    stages:
      - test
      - dev
      - offline
    start:
      inMemory: true
      migrate: true
  prefix: ${self:service}-${self:provider.stage}
  tableName: ${self:service}-ledgers
  serverless-offline:
    allowCache: true

package:
  # individually: true
  patterns:
    - '!node_modules/aws-sdk'
    - '!client'
    - '!tests'
    - '!src'
    - '!.dynamodb'

plugins:
  # - serverless-webpack
  # - serverless-dotenv-plugin
  # WARNING! This is serverless-dynamodb-local from https://github.com/99x/serverless-dynamodb-local
  # it is different from the official serverless docs!
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-stack-output

functions:
  graphql:
    handler: dist/server.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer
      - http:
          path: graphql
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer
    environment:
      DYN_TABLE: ${self:custom.tableName}
      DEBUG: ${self:custom.debug}
      NODE_DEBUG: ${env:NODE_DEBUG, 'sumsy*'}
      LOG_LEVEL: ${env:LOG_LEVEL, 'error'}
      LOG_PREFIX: sumsy
      ACCOUNT_TYPES: ${env:ACCOUNT_TYPES, '[{"type":"default","income":0,"buffer":0,"demurrage":2.5},{"type":"verified","income":0,"buffer":5,"demurrage":2.5},{"type":"guaranteed_income","income":16,"buffer":5,"demurrage":2.5},{"type":"professional","income":0,"buffer":5,"demurrage":0.5}]'}

resources:
  - ${file(resources/dynamo.yml)}
  - ${file(resources/client.yml)}
  - ${file(resources/cognito.yml)}
  - ${file(resources/exports.yml)}
  - ${file(resources/cloudfront.yml)}

