service: mani-backend

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1

plugins:
  # - serverless-webpack
  # Look out! This is serverless-dynamodb-local from https://github.com/99x/serverless-dynamodb-local
  # it is different from the official serverless docs!
  - serverless-dynamodb-local
  - serverless-offline 

resources:
  Resources:
    ledger:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: manipona
        AttributeDefinitions:
          - AttributeName: ledger
            AttributeType: S
          - AttributeName: entry
            AttributeType: S
        KeySchema:
          - AttributeName: ledger
            KeyType: HASH
          - AttributeName: entry
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

# Warning: the dynamodb shell does NOT work in Firefox, only in Chrome
custom:
  dynamodb:
    stages:
      - test
      - dev
    start:
      inMemory: true
      migrate: true
      seed: false
    seed:
      test:
        sources:
          - table: manipona
            sources: [./tests/seeds/manipona.json]

